spring:
  data:
    mongodb:
      uri: mongodb+srv://parthsharma2640:7817971083%40ps@cluster0.du0knbh.mongodb.net/?retryWrites=true&w=majority
      database: aibasedendtoendsystem
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB

server:
  port: 8081
  servlet:
    context-path: /api

  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: 100MB


app:
  oauth2:
    client:
      registration:
        google:
          provider: google
          client-id: 933277047426-lc7eeb96h30umrm6qfoncp6l27026s07.apps.googleusercontent.com
          client-secret: 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
          redirectUriForRecruiter: http://localhost:8081/api/recruiter/google/login
          redirectUriForCandidate: http://localhost:8081/api/candidate/google/login

app.config:
  url:
    baseUrl: https://localhost:8081/api
    frontEndUrl: http://localhost:3000
    hostFrontEndUrl: https://ai-based-endto-end-recruitment-syst.vercel.app

brevo:
  api:
     key: ${BREVO_API_KEY}
  sender:
    email: parthsharma7817@gmail.com


